"use client";

import { type FormEvent, useCallback, useEffect, useState } from "react";
import { ArrowLeft, Newspaper, Plus, Trash2 } from "lucide-react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import type { ContentItem } from "@/components/public-content";

export default function AdminDashboard({ userName, signOutPath }: { userName: string; signOutPath: string }) {
  const [items, setItems] = useState<ContentItem[]>([]); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false);
  const load=useCallback(()=>fetch("/api/content").then(r=>r.json()).then(setItems).catch(()=>setMessage("Could not load content.")),[]); useEffect(()=>{load()},[load]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage("");const form=e.currentTarget;const f=new FormData(form);const body=Object.fromEntries(f.entries());const r=await fetch("/api/content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setSaving(false);if(r.ok){form.reset();setMessage("Content published successfully.");load()}else setMessage("Please check all fields and try again.")}
  async function remove(id:number){const r=await fetch(`/api/content?id=${id}`,{method:"DELETE"});if(r.ok){setMessage("Content deleted.");load()}else setMessage("Could not delete this item.")}
  return <main className="admin-page"><header className="admin-top"><a href="/"><ArrowLeft/>Website</a><img src="/assets/lifeco-logo.png" alt="LIFECO"/><div><span>{userName}</span><a href={signOutPath}>Sign out</a></div></header><div className="admin-layout"><aside><Newspaper/><h1>Content manager</h1><p>Publish bilingual news and tender notices without editing the website code.</p></aside><div className="admin-workspace"><section className="admin-form-card"><div className="admin-card-heading"><Plus/><div><h2>Add content</h2><p>Both languages are required before publishing.</p></div></div><form onSubmit={submit}><div className="form-row"><label>Content type<select name="kind" defaultValue="news"><option value="news">News</option><option value="tender">Tender</option></select></label><label>Status<select name="status" defaultValue="published"><option value="published">Published</option><option value="draft">Draft</option></select></label></div><label>Date<input name="date" type="date" required/></label><div className="form-row"><label>English title<input name="titleEn" required/></label><label>العنوان العربي<input name="titleAr" dir="rtl" required/></label></div><div className="form-row"><label>English summary<textarea name="summaryEn" rows={4} required/></label><label>الملخص العربي<textarea name="summaryAr" dir="rtl" rows={4} required/></label></div><button className="primary-button" disabled={saving}>{saving?"Saving…":"Publish content"}</button>{message&&<p className="admin-message" role="status">{message}</p>}</form></section><section className="admin-list"><h2>Managed content</h2>{items.length===0?<p className="admin-empty">No managed items yet.</p>:items.map(item=><article key={item.id}><div><span className="status-pill">{item.kind} · {item.status}</span><h3>{item.titleEn}</h3><p>{item.date}</p></div><AlertDialog><AlertDialogTrigger asChild><button className="delete-button" aria-label={`Delete ${item.titleEn}`}><Trash2/></button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this content?</AlertDialogTitle><AlertDialogDescription>This permanently removes “{item.titleEn}” from the website.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={()=>remove(item.id)}>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></article>)}</section></div></div></main>;
}
