"use client";

import { ArrowUpRight } from "lucide-react";
import { PublicContent } from "@/components/public-content";
import { SubpageShell, useSiteLanguage } from "@/components/site-shell";

const official=[
 {dateEn:"25 APR 2026",dateAr:"25 أبريل 2026",titleEn:"Urea II exceeds 103% of its March production target",titleAr:"اليوريا الثاني يتجاوز 103% من مستهدف إنتاج مارس",summaryEn:"Production and maintenance teams delivered 46,537 metric tonnes of urea during March 2026.",summaryAr:"حققت فرق التشغيل والصيانة إنتاج 46,537 طنًا متريًا من اليوريا خلال مارس 2026.",href:"https://lifeco.com.ly/2026/04/25/%D8%A7%D9%84%D9%8A%D9%88%D8%B1%D9%8A%D8%A7-%D8%A7%D9%84%D8%AB%D8%A7%D9%86%D9%8A-%D9%8A%D8%B5%D9%84-%D8%A5%D9%84%D9%89-%D9%86%D8%B3%D8%A8%D8%A9-%D8%AA%D8%AC%D8%A7%D9%88%D8%B2%D8%AA-%D8%A7%D9%84%D9%80-1/"},
 {dateEn:"22 APR 2026",dateAr:"22 أبريل 2026",titleEn:"National Oil Corporation chairman visits LIFECO",titleAr:"رئيس المؤسسة الوطنية للنفط يزور لايفكو",summaryEn:"The visit reviewed operating conditions, production plans and the company’s technical and logistics priorities.",summaryAr:"تناولت الزيارة الموقف التشغيلي والخطط الإنتاجية والأولويات الفنية واللوجستية للشركة.",href:"https://lifeco.com.ly/2026/04/22/%D8%B1%D8%A6%D9%8A%D8%B3-%D8%A7%D9%84%D9%85%D8%A4%D8%B3%D8%B3%D8%A9-%D8%A7%D9%84%D9%88%D8%B7%D9%86%D9%8A%D8%A9-%D9%84%D9%84%D9%86%D9%81%D8%B7-%D9%8A%D9%82%D9%88%D9%85-%D8%A8%D8%B2%D9%8A%D8%A7%D8%B1/"},
 {dateEn:"17 APR 2026",dateAr:"17 أبريل 2026",titleEn:"LIFECO welcomes the NOC safety delegation",titleAr:"لايفكو تستقبل وفد إدارة السلامة بالمؤسسة",summaryEn:"A two-day field visit reviewed safety, environmental and occupational-health procedures.",summaryAr:"زيارة ميدانية لمدة يومين لمتابعة إجراءات السلامة والبيئة والصحة المهنية.",href:"https://lifeco.com.ly/2026/04/17/%D8%A7%D9%84%D9%84%D9%8A%D8%A8%D9%8A%D8%A9-%D9%84%D9%84%D8%A3%D8%B3%D9%85%D8%AF%D8%A9-%D8%AA%D8%B3%D8%AA%D9%82%D8%A8%D9%84-%D9%88%D9%81%D8%AF-%D9%85%D9%86-%D8%A5%D8%AF%D8%A7%D8%B1%D8%A9-%D8%A7%D9%84/"}
];
const c={en:{e:"Company newsroom",t:"News from LIFECO.",d:"Production milestones, visits and operational updates from the Al Brega complex.",latest:"Latest updates",official:"Read official story"},ar:{e:"المركز الإعلامي",t:"أخبار لايفكو.",d:"مستجدات الإنتاج والزيارات والعمليات من المجمع الصناعي في البريقة.",latest:"آخر المستجدات",official:"اقرأ الخبر الرسمي"}} as const;
export default function News(){const l=useSiteLanguage(),t=c[l.language],ar=l.isArabic;return <SubpageShell currentPath="/news" language={l.language} setLanguage={l.setLanguage} eyebrow={t.e} title={t.t} description={t.d} image="/assets/plant-aerial.jpg"><section className="section-pad news-section"><div className="page-width"><div className="archive-heading"><p className="eyebrow"><span/>{t.latest}</p></div><PublicContent kind="news" language={l.language}/><div className="news-archive-grid">{official.map((n,i)=><article className="news-feature-card" key={n.href}><div className="content-date"><span>0{i+1}</span><time>{ar?n.dateAr:n.dateEn}</time></div><div><span className="status-pill">LIFECO</span><h2>{ar?n.titleAr:n.titleEn}</h2><p>{ar?n.summaryAr:n.summaryEn}</p><a href={n.href} target="_blank" rel="noreferrer">{t.official}<ArrowUpRight/></a></div></article>)}</div></div></section></SubpageShell>}
