"use client";

import { ArrowUpRight, Check } from "lucide-react";
import { SubpageShell, useSiteLanguage } from "@/components/site-shell";

const copy={en:{e:"Our products",t:"Essential nitrogen products for agriculture and industry.",d:"Explore LIFECO’s two core products, produced through an integrated operation in Al Brega.",intro:"Product portfolio",heading:"One integrated production chain.",text:"Natural gas is transformed into ammonia, which becomes the principal feedstock for granular urea. This integrated process supports consistent production and efficient product movement.",urea:"Urea",ureaText:"White granular fertiliser with a minimum nitrogen content of 46.4%, designed for agricultural use and efficient bulk handling.",ammonia:"Ammonia",ammoniaText:"A foundational nitrogen product and the primary feedstock for LIFECO’s urea manufacturing process.",details:"View product details",points:["Local and international supply","Port-linked bulk logistics","Commercial coordination"]},ar:{e:"منتجاتنا",t:"منتجات نيتروجينية أساسية للزراعة والصناعة.",d:"تعرّف على منتجي لايفكو الرئيسيين اللذين يتم إنتاجهما ضمن عملية متكاملة في البريقة.",intro:"محفظة المنتجات",heading:"سلسلة إنتاج متكاملة واحدة.",text:"يُحوّل الغاز الطبيعي إلى أمونيا، لتصبح المادة الخام الرئيسية لإنتاج اليوريا الحبيبية. وتدعم هذه العملية المتكاملة استقرار الإنتاج وكفاءة حركة المنتجات.",urea:"اليوريا",ureaText:"سماد أبيض حبيبي بنسبة نيتروجين لا تقل عن 46.4%، مصمم للاستخدام الزراعي والمناولة الفعالة للمنتجات السائبة.",ammonia:"الأمونيا",ammoniaText:"منتج نيتروجيني أساسي والمادة الخام الرئيسية في عملية تصنيع اليوريا لدى لايفكو.",details:"تفاصيل المنتج",points:["توريد محلي ودولي","لوجستيات سائبة مرتبطة بالميناء","تنسيق تجاري"]}} as const;
export default function ProductsPage(){const lang=useSiteLanguage();const t=copy[lang.language];return <SubpageShell currentPath="/products" language={lang.language} setLanguage={lang.setLanguage} eyebrow={t.e} title={t.t} description={t.d} image="/assets/products-bg.jpg">
  <section className="section-pad intro-section"><div className="page-width product-intro-grid"><div><p className="eyebrow"><span />{t.intro}</p><h2>{t.heading}</h2></div><div><p className="lead-copy">{t.text}</p><ul className="clean-list">{t.points.map(p=><li key={p}><Check size={18}/>{p}</li>)}</ul></div></div></section>
  <section className="products-section section-pad"><div className="page-width product-grid"><a className="product-card" href="/products/urea"><img src="/assets/products-bg.jpg" alt="Granular urea"/><div className="product-overlay"/><div className="product-content"><span className="product-number">01</span><div><span className="formula">CO(NH₂)₂</span><h3>{t.urea}</h3><p>{t.ureaText}</p><span className="product-detail-link">{t.details}<ArrowUpRight/></span></div></div></a><a className="product-card product-ammonia" href="/products/ammonia"><div className="molecule"><strong>N</strong><span/><span/><span/></div><div className="product-content"><span className="product-number">02</span><div><span className="formula">NH₃</span><h3>{t.ammonia}</h3><p>{t.ammoniaText}</p><span className="product-detail-link">{t.details}<ArrowUpRight/></span></div></div></a></div></section>
  </SubpageShell>}
