"use client";

import { Factory, Leaf, ShieldCheck, Users } from "lucide-react";
import { SubpageShell, useSiteLanguage } from "@/components/site-shell";

const copy = {
  en: { eyebrow: "Who we are", title: "A Libyan industrial company with global reach.", desc: "LIFECO produces urea and ammonia from its integrated manufacturing complex in Al Brega.", profile: "Company profile", profileTitle: "Building value from Libyan resources.", profileText: "Established under Libyan Investment Law No. 9 of 2010, the Libyan Fertiliser Company manages strategic industrial assets, national capabilities and nitrogen-product supply for local and international customers.", ownership: "Ownership", owners: [["75%", "National Oil Corporation"], ["25%", "Libyan Investment Authority"]], vision: "Our direction", visionTitle: "Safe, reliable and internationally competitive production.", priorities: [["Safety", "Protecting people and plants through disciplined operations."], ["Reliability", "Improving efficiency and asset performance."], ["Environment", "Strengthening environmental controls and reducing emissions."], ["People", "Developing Libyan expertise through specialised training."]], leader: "Leadership", quote: "We work to protect LIFECO’s industrial assets, strengthen national capabilities and deliver trusted nitrogen products to customers in Libya and around the world.", name: "Hamad Arish Hamad", role: "Chief Executive Officer", management: "Management functions", functions: ["Operations & Maintenance", "Commercial & Marketing", "Finance & Administration", "Safety & Environment"] },
  ar: { eyebrow: "من نحن", title: "شركة صناعية ليبية بامتداد عالمي.", desc: "تنتج لايفكو اليوريا والأمونيا من مجمعها الصناعي المتكامل في البريقة.", profile: "نبذة عن الشركة", profileTitle: "صناعة القيمة من الموارد الليبية.", profileText: "تأسست الشركة الليبية للأسمدة بموجب قانون الاستثمار الليبي رقم 9 لسنة 2010، وتتولى إدارة أصول صناعية استراتيجية وتنمية الكفاءات الوطنية وتوريد المنتجات النيتروجينية للعملاء محليًا ودوليًا.", ownership: "هيكل الملكية", owners: [["75%", "المؤسسة الوطنية للنفط"], ["25%", "المؤسسة الليبية للاستثمار"]], vision: "توجهنا", visionTitle: "إنتاج آمن وموثوق وقادر على المنافسة عالميًا.", priorities: [["السلامة", "حماية العاملين والمصانع عبر التشغيل المنضبط."], ["الوثوقية", "رفع الكفاءة وتحسين أداء الأصول."], ["البيئة", "تطوير أنظمة التحكم البيئي والحد من الانبعاثات."], ["العاملون", "تنمية الخبرات الليبية من خلال التدريب المتخصص."]], leader: "الإدارة", quote: "نعمل على حماية أصول لايفكو الصناعية وتطوير القدرات الوطنية وتقديم منتجات نيتروجينية موثوقة للعملاء في ليبيا وحول العالم.", name: "حمد عريش حمد", role: "المدير التنفيذي", management: "الوظائف الإدارية", functions: ["التشغيل والصيانة", "التجارة والتسويق", "المالية والإدارة", "السلامة والبيئة"] },
} as const;

export default function CompanyPage() {
  const lang = useSiteLanguage(); const t = copy[lang.language]; const icons = [ShieldCheck, Factory, Leaf, Users];
  return <SubpageShell currentPath="/company" language={lang.language} setLanguage={lang.setLanguage} eyebrow={t.eyebrow} title={t.title} description={t.desc} image="/assets/operations.jpg">
    <section className="section-pad intro-section"><div className="page-width company-profile-grid"><div><p className="eyebrow"><span />{t.profile}</p><h2>{t.profileTitle}</h2></div><div><p className="lead-copy">{t.profileText}</p><h3 className="mini-title">{t.ownership}</h3><div className="ownership-grid">{t.owners.map(([value,label]) => <article key={value}><strong>{value}</strong><span>{label}</span></article>)}</div></div></div></section>
    <section className="section-pad responsibility-section"><div className="page-width"><div className="section-heading centered-heading"><p className="eyebrow"><span />{t.vision}</p><h2>{t.visionTitle}</h2></div><div className="priority-grid">{t.priorities.map(([title,text],i) => { const Icon=icons[i]; return <article className="priority-card" key={title}><div className="priority-top"><Icon/><span>0{i+1}</span></div><h3>{title}</h3><p>{text}</p></article>})}</div></div></section>
    <section className="leadership-section"><div className="page-width leadership-grid"><div className="leadership-heading"><p className="eyebrow light"><span />{t.leader}</p><h2>{t.name}</h2><p className="leader-role">{t.role}</p></div><div className="leadership-message"><span className="quote-mark">“</span><blockquote>{t.quote}</blockquote></div><div className="leadership-facts"><span>{t.management}</span>{t.functions.map(item => <article key={item}><strong>{item}</strong></article>)}</div></div></section>
  </SubpageShell>;
}
